[meta]
title = "Ralf's skillradar"
categories = [ "Tools", "Techniques", "Platforms & Languages", "Frameworks" ]
levels = [ "Novice", "Intermediate", "Advanced", "Veteran" ]
  
[[blips]]
category = 3
title = "Spock"
link = "http://spockframework.org/"
description= ""
level = 3

[[blips.changes]]
  date = "2019-06"
  newLevel = 3
  text = "initial setup"

[[blips]]
category = 2
title = "OpenShift"
level = 0

  [[blips.changes]]
  date = "2019-06"
  newLevel = 0
  text = "initial setup"

[[blips]]
category = 1
description = "Da Wasserfall eigentlich noch nie geklappt hat, haben wir in der Entwicklung eigentlich schon immer agil gearbeitet. Mit der zeit hat das dann Namen bekommen, wie eXtreme Programming und jetzt Scrum. Allerdings mache ich nicht Scrum by the Book, sondern nutze die Ansätze, so wie sie in das Projekt passen."
title = "Scrum"
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3
  reason = "initial setup"
  
[[blips]]
category = 1
title = "Everything as Code"
description = "Gerne, soweit es machbar und effizient ist"
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2
  reason = "initial setup"
  
[[blips]]
category = 1
link = "https://docs-as-co.de"
title = "Docs-as-Code"
description = "I not only use this approach, I also try to evolve and define it."
level = 3

  [[blips.changes]]
  date = "2019-06"
  newLevel = 3
  reason = "initial setup"

[[blips]]
category = 1
title = "Architecture Decision Records (ADRs)"
description = 'Sometimes in Chapter 9 of arc42 (Design Decisions), sometimes inline as comments (see also the book "Java by Comaprison") sometimes jsut as .adoc file.'
level = 2

  [[blips.changes]]
  date = "2019-06"
  newLevel = 2
  reason = "initial setup"
  
[[blips]]
category = 1
link = "https://arc42.org"
description = """
arc42 is the standard for software system architecture documentation. I not only use it, I also defined the converters behind the template mechanism.
One of my architectures is part of the book "arc42 by example"\
"""
title = "arc42"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 3
link = "https://gebish.org/"
description = "Geb is a really useful abstractionlayer on top of the selenium webdriver. It is ewasy to use and produces readable test code."
title = "Geb"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
description = "The JVM is is my preferred platform for enterprise development."
title = "JVM"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
description = """
Java ist the base languages on the JVM. I am a SCP for Java 5 :-) and started out with Java 1.something. 
Together with others, I organized decades ago the Java User Group Frankfurt.
I don't like Java"""
title = "Java"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
description = "Whenever I code on the Raspberry Pi, I use Python for its performance and resource management."
title = "Python"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
description = "Groovy is my preferred language because it is very flexible and it gives me the productivity I need."
title = "Groovy"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 0
description = """
Don't ask me for shortcuts. It just works and I live it.
Ultimate edition everywhere."""
title = "IntelliJ"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 0
description = "The preferred tool to write documentation."
title = "Asciidoctor"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 0
description = """
Use it mostly for complex architecture diagrams.
Export autoamted for documentation."""
title = "Sparx Enterprise Architect"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
description = """
JQuery for the win :-)
I know how to use it to achive things."""
title = "JavaScript"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
description = "For both, I had a full day workshop. That's it."
title = "Angular & React"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 1
description = """
I can write Microservices and Apps in Spring Boot, but never used it for production code.
I consider it as a too complex framework and prefere to use Grails"""
title = "Spring Boot"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 1
link = "https://docToolchain.github.io/docToolchain/"
description = "Mainter von docToolchain"
title = "docToolchain"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 1
description = "I use Spring Security for oAuth2 / OIDC login and manage to configure it without code."
title = "Spring Security"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 1
link = "https://grails.org"
description = "I used Grails 2.x for over 10 years for several applications in production."
title = "Grails"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 0
description = """
Configured and used it for oAuth2 / OIDC 
and for automated testing"""
title = "Keycloak"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 0
description = "Use it for docToolchain"
title = "Gradle"

  [[blips.changes]]
  date = "2019-06"

[[blips]]
category = 2
link = "https://golang.org"
description = "sldjkfsdlfk"
title = "Go"

  [[blips.changes]]
  date = "2019-06"
